#!/bin/sh

makezip()
{
  origdir=`pwd`
  NAME=luabidi
  TMPDIR=`mktemp -d /tmp/luabidiXXXXXX`
  TDSSUB=lualatex/luabidi/
  mkdir -p "$TMPDIR"/"$NAME"/tex
  mkdir -p "$TMPDIR"/"$NAME"/doc
  filename="$TMPDIR"/"$NAME".zip

  SRCDIR=`realpath \`dirname $0\``
  echo "source $SRCDIR"
  # First the flat structure
  cp -a README.md LICENCE.md "$TMPDIR"/"$NAME"
  cp -a tex/* "$TMPDIR"/"$NAME"/tex
  cp -a doc/* "$TMPDIR"/"$NAME"/doc

  # Compile documentation
  TEXINPUTS=$PWD/tex:$PWD/doc:
  cd "$TMPDIR"/"$NAME"/doc
  lualatex luabidi
  lualatex luabidi
  rm *.{glo,log,out,idx,aux,toc,hd} 2&> /dev/null

  # Now prepare the zip archive.
  ctanzip=$NAME.zip
  cd ../..
  zip -ry $ctanzip $NAME
}


if makezip; then
  mv -f $ctanzip $origdir/
  cd ..
  rm -rf $TMPDIR
  echo "$ctanzip ready to be shipped to CTAN."
else
  echo "Something went wrong."
fi
