#!/bin/sh

makezip()
{
  NAME=luabidi
  TMPDIR=`mktemp -d /tmp/luabidiXXXXXX`
  TDSSUB=lualatex/luabidi/
  mkdir -p "$TMPDIR"/"$NAME"/tex/"$TDSSUB"
  mkdir -p "$TMPDIR"/"$NAME"/doc/"$TDSSUB"
  filename="$TMPDIR"/"$NAME".zip

  SRCDIR=`realpath \`dirname $0\``
  echo "source $SRCDIR"
  cp -a README.md LICENCE.md "$TMPDIR"/"$NAME"
  cp -a tex/* "$TMPDIR"/"$NAME"/tex/"$TDSSUB"
  cp -a doc/* "$TMPDIR"/"$NAME"/doc/"$TDSSUB"
  cd "$TMPDIR"
  zip -ry $NAME.zip $NAME
}


if makezip; then
  echo "$filename ready to be shipped to CTAN."
else
  echo "Something went wrong."
fi
